### ISSUE TITLE
Gallery mode appears on textboards after latest update

### ISSUE THREAD

**Issue by kuz-sysadmin** [KolymaNET/kokonotsuba-js#1]
I used to fix this with some display: none; css

**Comment by Barry-Cool** [comment]
Maybe don't include img.js on the textboard templates, since there are no images, and it's img.js that makes the gallery mode button.

**Comment by Barry-Cool** [comment]
Removing the img.js on the kokotxt(reply).tpl works, please apply, my template files are modified too much to commit
